# __manifest__.py
{
    'name': 'Employee Purchase Requisition Advanced',
    'version': '1.0',
    'category': 'Purchases',
    'summary': 'Manage employee purchase requisitions with multi-level approvals, vendor suggestions, and analytics',
    'author': 'Your Name',
    'website': 'https://yourcompany.com',
    'license': 'AGPL-3',
    'depends': ['base', 'mail', 'purchase', 'stock', 'hr', 'account'],
    'data': [
        'security/requisition_security.xml',
        'security/ir.model.access.csv',
        'data/sequence_data.xml',
        'views/requisition_views.xml',
        'reports/employee_requisition_report.xml',
        'wizard/requisition_report_wizard_view.xml',
        'wizard/Vendor_selection_wizard_view.xml',
        'views/requisition_actions.xml',
        'views/requisition_dashboard.xml',
        'views/product_template.xml',
        'data/email_templates.xml',
    ],
    'images': ['static/description/icon.png'],
    'installable': True,
    'application': True,
    'price': 199.99,
    'currency': 'USD',
}